# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-08-29 13:05
from __future__ import unicode_literals

import ImageReader.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageUploads',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to=ImageReader.models.get_file_path)),
                ('status', models.IntegerField(default=0)),
                ('filename', models.CharField(max_length=50)),
            ],
        ),
    ]
